apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-mongo-ruby
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-mongo-ruby
  template:
    metadata:
      labels:
        app: kube-mongo-ruby
    spec:
      containers:
      - image: localhost:5000/kube-mongo-ruby:latest
        name: ruby-app
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: RACK_ENV
          value: production
        - name: MONGO_DATABASE
          valueFrom: 
            secretKeyRef:
              name: mongosecret
              key: mongo_database
        - name: MONGO_USER
          valueFrom: 
            secretKeyRef:
              name: mongosecret
              key: mongo_user
        - name: MONGO_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongosecret
              key: mongo_password



---

apiVersion: v1
kind: Service
metadata:
  name: kube-mongo-ruby
spec:
  type: NodePort
  ports:
  - name: "kube-mongo-ruby"
    port: 8080
    targetPort: 8080
    nodePort: 30000
  selector:
    app: kube-mongo-ruby
